language: node_js
node_js:
  - "v6"
  - "v7"
  - "v8"
env:
  - CODECLIMATE_REPO_TOKEN=7ba98aca9f50871c9d498b22b2f7f11cc780e4894a93127e843eecd6307588ba
matrix:
  notifications:
    email:
      recipients:
        - ike18t@gmail.com
      on_success: change
      on_failure: change
after_success:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
